sudo: required
language: node_js
cache:
  yarn: true
notifications:
  email: false
branches:
  only:
    - master
node_js:
  - "8"
  - "6"
services:
  - docker
env:
  global:
    - COUCHBASE_USER="Administrator"
    - COUCHBASE_PASS="password"
  matrix:
    - COUCHBASE="couchbase4"
    - COUCHBASE="couchbase3"
before_script:
  - ./dockers/start-couchbase.sh
script:
  - make test-coveralls
