sudo: required
language: node_js
cache:
  yarn: true
notifications:
  email: false
branches:
  only:
    - master
node_js:
  - "10"
  - "8"
services:
  - docker
env:
  global:
    - COUCHBASE_USER="Administrator"
    - COUCHBASE_PASS="password"
script:
  - yarn test
