sudo: required
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
node_js:
  - "6"
  - "4"
services:
  - docker
env:
  global:
    - COUCHBASE_USER="Administrator"
    - COUCHBASE_PASS="password"
  matrix:
    - COUCHBASE="couchbase4"
    - COUCHBASE="couchbase3"
before_install:
  - ./dockers/start-couchbase.sh
install:
  - npm install
before_script:
  - npm prune
script:
  - make test-coveralls
