sudo: required
language: node_js
cache:
  yarn: true
notifications:
  email: false
branches:
  only:
    - master
node_js:
  - "10"
  - "8"
services:
  - docker
env:
  global:
    - COUCHBASE_USER="Administrator"
    - COUCHBASE_PASS="password"
  matrix:
    - COUCHBASE="cb4"
    - COUCHBASE="cb5"
    - COUCHBASE="cb6"
before_script:
  - ./dockers/up.sh $COUCHBASE
script:
  - make test-coveralls
